#!/bin/bash

PROJECT="puppetserver"

mkdir -p builds
if [ ! -d "builds/$PROJECT" ]; then
    pushd builds
    git clone "https://github.com/ehelms/$PROJECT"
    popd
fi

cd "builds/$PROJECT"
git checkout 7.x-patches
mkdir -p output
podman run --volume ./:/code:Z --workdir /code ezbake-builder:7 "build-$PROJECT"
