#!/bin/bash

PROJECT="puppetserver"

mkdir -p builds
if [ ! -d "builds/$PROJECT" ]; then
    cd builds && git clone "https://github.com/ehelms/$PROJECT"
fi

cd "$PROJECT"
git checkout 7.x-patches
mkdir -p output
podman run --volume ./:/code:Z --workdir /code ezbake-builder:7 "build-$PROJECT"
