#!/bin/bash -xe

rm -rf ruby && rm -rf output && bundle install --without test && lein install

COW="" MOCK="pl-el-8-x86_64" GEM_SOURCE='https://rubygems.org' EZBAKE_ALLOW_UNREPRODUCIBLE_BUILDS=true EZBAKE_NODEPLOY=true LEIN_PROFILES=ezbake lein with-profile user,ezbake,provided,internal ezbake local-build
